### ISSUE TITLE
Uncaught exception when cache file contains invalid JSON

### ISSUE THREAD

**Issue by feross** [royriojas/flat-cache#12]
When you call `readJSON()` on [this line](https://github.com/royriojas/flat-cache/blob/1c2b1f7d101790eb75049afd02c6005bf7bfded4/cache.js#L25), there is a chance that an exception will be thrown, since `JSON.parse()` is called under-the-hood.

`JSON.parse()` calls should be wrapped in a `try-catch` block in case the string can't be parsed as JSON. This can happen if another program creates/modifies the cache file, or if the node script using `flat-cache` crashes in the middle of a write.

This issue is currently affecting ESLint (https://github.com/eslint/eslint/issues/7748) and standard (https://github.com/feross/standard/issues/673). More details in the linked issues.

**Comment by royriojas** [comment]
Hi @feross, thanks for reporting it, will take a look.

**Comment by royriojas** [comment]
Hi @feross, a new patch version was published, should fix the issue in Eslint.

**Comment by feross** [comment]
@royriojas Excellent, thanks!
