### ISSUE TITLE
Data had been replaced with "NUL" characters

### ISSUE THREAD

**Issue by partha-srivi** [royriojas/flat-cache#17]
Hi, 

I am using flat-cache, as a offline storage in an application developed using electron. Sometime, the content in cache file was completely or partially replaced with "NUL" characters. I could not identify the cause for this. Could you please suggest a solution for this?

thanks,
Partha

**Comment by royriojas** [comment]
hi @partha-srivi 

Can you provide a code sample that shows this behavior? I have some unit tests covering the module and haven't notice that behavior, so any help reproducing the issue will be awesome

Thanks

**Comment by royriojas** [comment]
Closing this as this behavior has not been reported more and no repro case was provided. Please feel free to reopen if you feel this is still an issue.
