### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by coreyfarrell** [royriojas/flat-cache#18]
Hello, before I spend time preparing a PR I'd like to know if you willing to accept patches which make this and a few other modules require node 4?  I'm working through some dependency trees for node modules and trying to eliminate situations where multiple versions of the same module are installed.  The current versions of many dependencies now require node >=4.

**Comment by royriojas** [comment]
I'm seriously considering removing the `graceful-fs` and `write` dependencies as they can be done with the default `fs` module now. Will create tickets for that and review which versions of node are needed to support.

**Comment by coreyfarrell** [comment]
Closing this since all production dependencies are up to date and you have a separate ticket for removing `write`.
