### ISSUE TITLE
`pinkie-promise` was deleted

### ISSUE THREAD

**Issue by odarbelaeze** [royriojas/flat-cache#19]
Hi there,

Do you mind updating `del` to version `3.0.0`, looks like the version we have pinned here depends on `pinkie-promise` and this one was deleted.

Cheers,

Oscar

**Comment by odarbelaeze** [comment]
Looks like `del` need to update `globby` https://github.com/sindresorhus/del/issues/63

**Comment by royriojas** [comment]
hi @odarbelaeze it seems the packages were put back again in the registry.

**Comment by odarbelaeze** [comment]
Don't need, yet if you want 😄

**Comment by royriojas** [comment]
it seems #26 fixes this ticket
