### ISSUE TITLE
circular-json dependency is marked as deprecated

### ISSUE THREAD

**Issue by rogierschouten** [royriojas/flat-cache#34]
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor

**Comment by royriojas** [comment]
hi @rogierschouten thanks for filing the bug, but this is something that was already filed and a PR was done for it. We had to revert it though due to some issues we caused in eslint. 

https://github.com/royriojas/flat-cache/issues/22

So let's use that issue instead of this one.

Kind regards
